package view;


import bean.FuncionarioBean;
import connection.ConnectionFactory;
import dao.FuncionarioDao;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Aluno
 */
public class CadastroFun extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFun
     */
    public CadastroFun() {
        initComponents();
        
        URL caminhoIcone = getClass().getResource("/img/Logo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        Date da = new Date();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd / MM / YYYY"); 
        data.setText(formato.format(da));
        
        Timer t = new Timer(1000,new view.CadastroFun.horas());
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomef = new javax.swing.JTextField();
        userf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        senhaf = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        emailf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        endf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        uff = new javax.swing.JComboBox<>();
        cargof = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cpff = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        voltar = new javax.swing.JLabel();
        cadastrar = new javax.swing.JLabel();
        pesquisar = new javax.swing.JLabel();
        atualizar = new javax.swing.JLabel();
        deletar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setResizable(false);
        getContentPane().setLayout(null);

        data.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(data);
        data.setBounds(680, 10, 90, 20);

        hora.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(hora);
        hora.setBounds(590, 10, 80, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Nome:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 120, 40, 15);

        nomef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomefActionPerformed(evt);
            }
        });
        getContentPane().add(nomef);
        nomef.setBounds(150, 140, 195, 30);
        getContentPane().add(userf);
        userf.setBounds(470, 140, 125, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 120, 68, 15);
        getContentPane().add(senhaf);
        senhaf.setBounds(470, 200, 195, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 180, 60, 15);
        getContentPane().add(emailf);
        emailf.setBounds(150, 200, 195, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 180, 52, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Endereço:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 240, 64, 15);

        endf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endfActionPerformed(evt);
            }
        });
        getContentPane().add(endf);
        endf.setBounds(150, 260, 195, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("UF:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 300, 20, 15);

        uff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "MA", "CE", "ES", "GO" }));
        uff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uffActionPerformed(evt);
            }
        });
        getContentPane().add(uff);
        uff.setBounds(150, 320, 120, 30);

        cargof.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Embalador", "Caixa", "Repositor" }));
        cargof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargofActionPerformed(evt);
            }
        });
        getContentPane().add(cargof);
        cargof.setBounds(470, 320, 121, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Cargo:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 300, 41, 15);

        try {
            cpff.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cpff);
        cpff.setBounds(470, 260, 195, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("CPF:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(470, 240, 27, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Clique aqui para");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 440, 120, 20);

        voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 0, 0));
        voltar.setText("voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(440, 440, 50, 20);

        cadastrar.setText("   Cadastrar   ");
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(190, 390, 90, 30);

        pesquisar.setText("     Pesquisar");
        pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(310, 390, 100, 30);

        atualizar.setText("     Atualizar");
        atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarMouseClicked(evt);
            }
        });
        getContentPane().add(atualizar);
        atualizar.setBounds(440, 390, 90, 30);

        deletar.setText("       Deletar");
        deletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletarMouseClicked(evt);
            }
        });
        getContentPane().add(deletar);
        deletar.setBounds(550, 390, 90, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("x");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 0, 20, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadastro de funtionario.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, -20, 910, 540);

        setSize(new java.awt.Dimension(790, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomefActionPerformed

    private void endfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endfActionPerformed

    private void uffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uffActionPerformed

    private void cargofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargofActionPerformed

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        // TODO add your handling code here:
        HomeAdm tp = new HomeAdm();
        dispose();
        tp.setVisible(true);
    }//GEN-LAST:event_voltarMouseClicked

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        
        try{
 
            FuncionarioBean fb = new FuncionarioBean();
            FuncionarioDao fd = new FuncionarioDao();
            int id = Integer.parseInt(JOptionPane.showInputDialog("Digite um ID valido para seu funcionario:"));
            
            if(uff.getSelectedItem() == "Selecione" || cargof.getSelectedItem() == "Selecione" || nomef.getText().trim().isEmpty() || emailf.getText().trim().isEmpty() || endf.getText().trim().isEmpty() || userf.getText().trim().isEmpty() || senhaf.getText().trim().isEmpty() || cpff.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos ou selecione todas as caixas de texto!");
            }
            else{
            fb.setNome(nomef.getText());
            fb.setEmail(emailf.getText());
            fb.setEndereco(endf.getText());
            fb.setUf((String)uff.getSelectedItem());
            fb.setUsername(userf.getText());
            fb.setSenha(String.valueOf(senhaf.getPassword()));
            fb.setCpf(cpff.getText());
            fb.setCargo((String)cargof.getSelectedItem());
            fb.setId((id));
            

            fd.create(fb);

            nomef.setText("");
            emailf.setText("");
            endf.setText("");
            uff.setSelectedIndex(0);
            userf.setText("");
            senhaf.setText("");
            cpff.setText("");
            cargof.setSelectedIndex(0);
            
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_cadastrarMouseClicked

    private void pesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarMouseClicked
        FuncionarioBean cb = new FuncionarioBean();
        FuncionarioDao cd = new FuncionarioDao();
        int id = Integer.parseInt(JOptionPane.showInputDialog("Digite seu ID:"));
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try {
            
            stmt = con.prepareStatement("SELECT * FROM funcionarios WHERE id = "+id);
            rs = stmt.executeQuery();
            while(rs.next()){

                
                nomef.setText(rs.getString("nome"));
                emailf.setText(rs.getString("email"));
                endf.setText(rs.getString("endereco"));
                uff.setSelectedItem(rs.getString("uf"));
                userf.setText(rs.getString("username"));
                senhaf.setText(rs.getString("senha"));
                cpff.setText(rs.getString("cpf"));
                cargof.setSelectedItem(rs.getString("cargo"));

            }
        }catch (SQLException ex ) {
            JOptionPane.showMessageDialog(null,"ID não existente!!");
        } 
        finally{
            connection.ConnectionFactory.closeConnection(con, stmt, rs);
        }
        
    }//GEN-LAST:event_pesquisarMouseClicked

    private void atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarMouseClicked
        try{
            FuncionarioBean fb = new FuncionarioBean();
            FuncionarioDao fd = new FuncionarioDao();

            int id = Integer.parseInt(JOptionPane.showInputDialog("Digite seu ID: "));
            if(uff.getSelectedItem() == "Selecione" || cargof.getSelectedItem() == "Selecione" || nomef.getText().trim().isEmpty() || emailf.getText().trim().isEmpty() || endf.getText().trim().isEmpty() || userf.getText().trim().isEmpty() || senhaf.getText().trim().isEmpty() || cpff.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos ou selecione todas as caixas de texto!");
            }
            else{
            fb.setId(id);
            fb.setNome(nomef.getText());
            fb.setEmail(emailf.getText());
            fb.setEndereco(endf.getText());
            fb.setUf((String)uff.getSelectedItem());
            fb.setUsername(userf.getText());
            fb.setSenha(String.valueOf(senhaf.getPassword()));
            fb.setCpf(cpff.getText());
            fb.setCargo((String)cargof.getSelectedItem());

            fd.Update(fb);

            nomef.setText("");
            emailf.setText("");
            endf.setText("");
            uff.setSelectedIndex(0);
            userf.setText("");
            senhaf.setText("");
            cpff.setText("");
            cargof.setSelectedIndex(0);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos ou insira um ID valido!");
        }
    }//GEN-LAST:event_atualizarMouseClicked

    private void deletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletarMouseClicked

        try{   
  
        FuncionarioBean fb = new FuncionarioBean();
        FuncionarioDao fd = new FuncionarioDao();

            int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o seu ID para deletar o cadastro do seu funcionario:"));

            fb.setId(id);

            fd.delete(fb);

            nomef.setText("");
            emailf.setText("");
            endf.setText("");
            uff.setSelectedIndex(0);
            userf.setText("");
            senhaf.setText("");
            cpff.setText("");
            cargof.setSelectedIndex(0);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ID invalido!");
        }
    }//GEN-LAST:event_deletarMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel atualizar;
    private javax.swing.JLabel cadastrar;
    private javax.swing.JComboBox<String> cargof;
    private javax.swing.JFormattedTextField cpff;
    private javax.swing.JLabel data;
    private javax.swing.JLabel deletar;
    private javax.swing.JTextField emailf;
    private javax.swing.JTextField endf;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomef;
    private javax.swing.JLabel pesquisar;
    private javax.swing.JPasswordField senhaf;
    private javax.swing.JComboBox<String> uff;
    private javax.swing.JTextField userf;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
 public class horas implements ActionListener{
    @Override
    public void actionPerformed (ActionEvent e){
        Calendar c = Calendar.getInstance();
        hora.setText(String.format("%1$tH:%1$tM:%1$tS", c));
    }
    }
}
