/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import dao.ProdutoDao;
import bean.ProdutosBean;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class CompraCli extends javax.swing.JFrame {

    /**
     * Creates new form Produtos
     */
    public CompraCli() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Produto.getModel();
        Tabela_Produto.setRowSorter(new TableRowSorter(modelo));
        
        Date da = new Date();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd / MM / YYYY"); 
        data.setText(formato.format(da));
        
        URL caminhoIcone = getClass().getResource("/img/Logo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        
readJTable();
       Timer t = new Timer(1000,new view.CompraCli.horas());
        t.start();
    }
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Produto.getModel();
        modelo.setNumRows(0);
        ProdutoDao cdao = new ProdutoDao();

        for (ProdutosBean p : cdao.read()) {

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getPreco(),
                p.getQtd(),
                p.getCat(),
                p.getForn(),
                p.getMarca(),
            });

        } 

    }
public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Produto.getModel();
        modelo.setNumRows(0);
        ProdutoDao cdao = new ProdutoDao();

        for (ProdutosBean p : cdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNome(),
                p.getPreco(),
                p.getQtd(),
                p.getCat(),
                p.getForn(),
                p.getMarca(),
            });

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Produto = new javax.swing.JTable();
        data = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        Comprar = new javax.swing.JLabel();
        Text_1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Total_T1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Text_2 = new javax.swing.JTextField();
        estoque = new javax.swing.JTextField();
        Campo_Busca = new javax.swing.JTextField();
        Botao_Busca = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Ok = new javax.swing.JButton();
        Sair1 = new javax.swing.JLabel();
        Text_4 = new javax.swing.JTextField();
        Text_6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Text_7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();
        Text_5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabela_Produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Preço", "Quantidade", "Categoria", "Fonercedor", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_ProdutoMouseClicked(evt);
            }
        });
        Tabela_Produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tabela_ProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Produto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 680, 130));

        data.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 110, 40));

        hora.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 90, 40));

        Comprar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Comprar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Comprar.setText("OK");
        Comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarMouseClicked(evt);
            }
        });
        jPanel1.add(Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 80, 30));

        Text_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_1FocusGained(evt);
            }
        });
        Text_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_1MouseClicked(evt);
            }
        });
        Text_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_1ActionPerformed(evt);
            }
        });
        jPanel1.add(Text_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Valor Total");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 110, 30));

        Total_T1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Total_T1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Total_T1FocusGained(evt);
            }
        });
        Total_T1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Total_T1MouseClicked(evt);
            }
        });
        jPanel1.add(Total_T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Valor Unidade");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 120, 30));

        Text_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_2FocusGained(evt);
            }
        });
        Text_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_2MouseClicked(evt);
            }
        });
        Text_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_2ActionPerformed(evt);
            }
        });
        jPanel1.add(Text_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 80, 30));

        estoque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estoque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                estoqueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                estoqueFocusLost(evt);
            }
        });
        estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estoqueMouseClicked(evt);
            }
        });
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        jPanel1.add(estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 50, 30));

        Campo_Busca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Campo_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 70, 150, 30));

        Botao_Busca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Botao_Busca.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Busca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Botao_Busca.setText("BUSCAR");
        Botao_Busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao_BuscaMouseClicked(evt);
            }
        });
        jPanel1.add(Botao_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Estoque");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 70, 30));

        Ok.setText("OK");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        jPanel1.add(Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 50, 30));

        Sair1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Sair1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sair1.setText("Voltar");
        Sair1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sair1MouseClicked(evt);
            }
        });
        jPanel1.add(Sair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 80, 30));

        Text_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_4FocusGained(evt);
            }
        });
        Text_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_4MouseClicked(evt);
            }
        });
        Text_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_4ActionPerformed(evt);
            }
        });
        jPanel1.add(Text_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 110, 30));

        Text_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_6FocusGained(evt);
            }
        });
        Text_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_6MouseClicked(evt);
            }
        });
        Text_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_6ActionPerformed(evt);
            }
        });
        jPanel1.add(Text_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Quantidade");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 90, 30));

        Text_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_7FocusLost(evt);
            }
        });
        Text_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_7MouseClicked(evt);
            }
        });
        Text_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_7ActionPerformed(evt);
            }
        });
        jPanel1.add(Text_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nome");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 50, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Marca");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 50, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Categoria");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 80, 30));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("x");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/T_Vendas.png"))); // NOI18N
        jPanel1.add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 840, 520));

        Text_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Text_5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_5FocusGained(evt);
            }
        });
        Text_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_5MouseClicked(evt);
            }
        });
        Text_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_5ActionPerformed(evt);
            }
        });
        jPanel1.add(Text_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        setSize(new java.awt.Dimension(806, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tabela_ProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_ProdutoMouseClicked
        // TODO add your handling code here:
        if (Tabela_Produto.getSelectedRow() != -1) {

            Text_1.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 1).toString());
            Text_2.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 2).toString());
            estoque.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 3).toString());
            Text_4.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 4).toString());
            Text_5.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 5).toString());
            Text_6.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 6).toString());
            
            /*float Total;
            Total = Float.parseFloat(Text_2.getText()) * Integer.parseInt(Text_3.getText());
            Total_T1.setText(String.valueOf(Total));*/
            

        }
        
        
        
    }//GEN-LAST:event_Tabela_ProdutoMouseClicked

    private void Tabela_ProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabela_ProdutoKeyReleased
        // TODO add your handling code here:
        if (Tabela_Produto.getSelectedRow() != -1) {

            Text_1.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 1).toString());
            Text_2.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 2).toString());
            estoque.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 3).toString());
            Text_4.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 4).toString());   
            Text_5.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 5).toString());
            Text_6.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 6).toString());
            

        }
        
    }//GEN-LAST:event_Tabela_ProdutoKeyReleased

    private void Botao_BuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao_BuscaMouseClicked
        // TODO add your handling code here:
        readJTableForDesc(Campo_Busca.getText());
        
            Text_1.setText("");
            Text_2.setText("");
            estoque.setText("");
           
        
        

    }//GEN-LAST:event_Botao_BuscaMouseClicked

    private void estoqueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_estoqueFocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_estoqueFocusGained

    private void estoqueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_estoqueFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_estoqueFocusLost

    private void Text_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_1ActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_Text_1ActionPerformed

    private void Text_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_1FocusGained

    private void Text_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_2FocusGained

    private void Total_T1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Total_T1FocusGained
        // TODO add your handling code here
    }//GEN-LAST:event_Total_T1FocusGained

    private void Total_T1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Total_T1MouseClicked
        // TODO add your handling code here:
        Total_T1.setEditable(false);
    }//GEN-LAST:event_Total_T1MouseClicked

    private void Text_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_2ActionPerformed

    private void Text_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_2MouseClicked
        // TODO add your handling code here:
        Text_2.setEditable(false);
    }//GEN-LAST:event_Text_2MouseClicked

    private void Text_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_1MouseClicked
        // TODO add your handling code here:
        Text_1.setEditable(false);
    }//GEN-LAST:event_Text_1MouseClicked

    private void ComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarMouseClicked
        // TODO add your handling code here:
        int Qtde = Integer.parseInt(estoque.getText()) - Integer.parseInt(Text_7.getText());
            estoque.setText(String.valueOf(Qtde));
        if (Tabela_Produto.getSelectedRow() != -1) {
        ProdutosBean p = new ProdutosBean();
        ProdutoDao dao = new ProdutoDao();
        p.setNome(Text_1.getText());        
        p.setPreco(Double.parseDouble(Text_2.getText()));
        p.setQtd(Integer.parseInt(estoque.getText()));
        p.setCat(Text_4.getText());
        p.setForn(Text_5.getText());
        p.setMarca(Text_6.getText());
        p.setCodigo((int)Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 0));
        
        dao.updateC(p);
        
        

        Text_1.setText("");
        Text_2.setText("");
        estoque.setText("");
        Text_4.setText("");
        Text_5.setText("");
        Text_6.setText("");
        Text_7.setText("");
        Total_T1.setText("");

        readJTable();

        }

    }//GEN-LAST:event_ComprarMouseClicked

    private void Sair1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sair1MouseClicked
    HomeCli tp = new HomeCli();
    dispose();
    tp.setVisible(true);
    }//GEN-LAST:event_Sair1MouseClicked

    private void Text_4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_4FocusGained

    private void Text_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_4MouseClicked
        // TODO add your handling code here:
        Text_4.setEditable(false);
        
    }//GEN-LAST:event_Text_4MouseClicked

    private void Text_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_4ActionPerformed

    private void Text_6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_6FocusGained

    private void Text_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_6MouseClicked
        // TODO add your handling code here:
        Text_6.setEditable(false);
    }//GEN-LAST:event_Text_6MouseClicked

    private void Text_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_6ActionPerformed

    private void Text_7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_7FocusGained

    private void Text_7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_7FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Text_7FocusLost

    private void estoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estoqueMouseClicked
        estoque.setEnabled(false);
    }//GEN-LAST:event_estoqueMouseClicked

    private void Text_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_7ActionPerformed

    private void Text_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_7MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Text_7MouseClicked

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
    
    }//GEN-LAST:event_estoqueActionPerformed

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
            int QTD = Integer.parseInt(Text_7.getText());
            int QTD2 = Integer.parseInt(estoque.getText()) - Integer.parseInt(Text_7.getText());
            
            if(QTD2 >= 0){ 
            float Total;
            Total = Float.parseFloat(Text_2.getText()) * Integer.parseInt(Text_7.getText());
            
            
            Total_T1.setText(String.valueOf(Total));
            }else if(QTD < 1){
            
                JOptionPane.showMessageDialog(null, "Valor inválido");
            }else{
            
            
            JOptionPane.showMessageDialog(null, "ERRO limite de Estoque !");
            }
            
        
        
    }//GEN-LAST:event_OkActionPerformed

    private void Text_5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_5FocusGained

    private void Text_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_5MouseClicked
        // TODO add your handling code here:
        Text_5.setEditable(false);
    }//GEN-LAST:event_Text_5MouseClicked

    private void Text_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_5ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraCli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Botao_Busca;
    private javax.swing.JTextField Campo_Busca;
    private javax.swing.JLabel Comprar;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton Ok;
    private javax.swing.JLabel Sair1;
    private javax.swing.JTable Tabela_Produto;
    private javax.swing.JTextField Text_1;
    private javax.swing.JTextField Text_2;
    private javax.swing.JTextField Text_4;
    private javax.swing.JTextField Text_5;
    private javax.swing.JTextField Text_6;
    private javax.swing.JTextField Text_7;
    private javax.swing.JTextField Total_T1;
    private javax.swing.JLabel data;
    private javax.swing.JTextField estoque;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public class horas implements ActionListener{
    @Override
    public void actionPerformed (ActionEvent e){
        Calendar c = Calendar.getInstance();
        hora.setText(String.format("%1$tH:%1$tM:%1$tS", c));
    }
    }
}
