/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.FornecedorBean;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import dao.ProdutoDao;
import bean.ProdutosBean;
import dao.FornecedorDao;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class Fornecedor extends javax.swing.JFrame {
    CadastroPro enviatexto;
    /**
     * Creates new form Produtos
     */
    public Fornecedor() {
        initComponents();
        
        Date da = new Date();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd / MM / YYYY"); 
        data.setText(formato.format(da));
        
        Timer t = new Timer(1000,new view.Fornecedor.horas());
        t.start();
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Produto.getModel();
        Tabela_Produto.setRowSorter(new TableRowSorter(modelo));

        
        URL caminhoIcone = getClass().getResource("/img/Logo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        
readJTable();

    }
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Produto.getModel();
        modelo.setNumRows(0);
        FornecedorDao cdao = new FornecedorDao();

        for (FornecedorBean p : cdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getMarca(),
                p.getCat(),

            });

        } 

    }
public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela_Produto.getModel();
        modelo.setNumRows(0);
        FornecedorDao cdao = new FornecedorDao();

        for (FornecedorBean p : cdao.readForDesc(desc)) {


            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getMarca(),
                p.getCat(),

            });

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Produto = new javax.swing.JTable();
        Campo_Busca = new javax.swing.JTextField();
        Botao_Busca = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        catf = new javax.swing.JTextField();
        marcaf = new javax.swing.JTextField();
        nomef = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabela_Produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Marca", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_ProdutoMouseClicked(evt);
            }
        });
        Tabela_Produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tabela_ProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Produto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 680, 130));

        Campo_Busca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Campo_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 150, 30));

        Botao_Busca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Botao_Busca.setForeground(java.awt.Color.black);
        Botao_Busca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Botao_Busca.setText("Buscar");
        Botao_Busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao_BuscaMouseClicked(evt);
            }
        });
        jPanel1.add(Botao_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 90, 30));

        data.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 110, 30));

        hora.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 17, 90, 30));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("x");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Produtos.png"))); // NOI18N
        jPanel1.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 820, 520));

        catf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        catf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                catfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                catfFocusLost(evt);
            }
        });
        catf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catfMouseClicked(evt);
            }
        });
        catf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catfActionPerformed(evt);
            }
        });
        jPanel1.add(catf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 130, 30));

        marcaf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        marcaf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                marcafFocusGained(evt);
            }
        });
        marcaf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marcafMouseClicked(evt);
            }
        });
        marcaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcafActionPerformed(evt);
            }
        });
        jPanel1.add(marcaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 130, 30));

        nomef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomef.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomefFocusGained(evt);
            }
        });
        nomef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomefMouseClicked(evt);
            }
        });
        nomef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomefActionPerformed(evt);
            }
        });
        jPanel1.add(nomef, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        setSize(new java.awt.Dimension(800, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tabela_ProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_ProdutoMouseClicked
        // TODO add your handling code here:
        if (Tabela_Produto.getSelectedRow() != -1) {

            nomef.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 1).toString());
            marcaf.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 2).toString());
            catf.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 3).toString());
            if(enviatexto == null){
            
                enviatexto = new CadastroPro();
                enviatexto.setVisible(true);
                enviatexto.recebendo(nomef.getText(), marcaf.getText(), catf.getText());
                dispose();
            }
            
            /*float Total;
            Total = Float.parseFloat(Text_2.getText()) * Integer.parseInt(Text_3.getText());
            Total_T1.setText(String.valueOf(Total));*/
            

        }
        
        
        
    }//GEN-LAST:event_Tabela_ProdutoMouseClicked

    private void Tabela_ProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabela_ProdutoKeyReleased
        // TODO add your handling code here:
        if (Tabela_Produto.getSelectedRow() != -1) {

            nomef.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 1).toString());
            marcaf.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 2).toString());
            catf.setText(Tabela_Produto.getValueAt(Tabela_Produto.getSelectedRow(), 3).toString());

            

        }
        
    }//GEN-LAST:event_Tabela_ProdutoKeyReleased

    private void Botao_BuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao_BuscaMouseClicked
        // TODO add your handling code here:
        readJTableForDesc(Campo_Busca.getText());
        
            nomef.setText("");
            marcaf.setText("");
            catf.setText("");
           
        
        

    }//GEN-LAST:event_Botao_BuscaMouseClicked

    private void catfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catfFocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_catfFocusGained

    private void catfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_catfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_catfFocusLost

    private void nomefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomefActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_nomefActionPerformed

    private void nomefFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomefFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nomefFocusGained

    private void marcafFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_marcafFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_marcafFocusGained

    private void marcafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcafActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcafActionPerformed

    private void marcafMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcafMouseClicked
        // TODO add your handling code here:
        marcaf.setEditable(false);
    }//GEN-LAST:event_marcafMouseClicked

    private void nomefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomefMouseClicked
        // TODO add your handling code here:
        nomef.setEditable(false);
    }//GEN-LAST:event_nomefMouseClicked

    private void catfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catfMouseClicked
        catf.setEnabled(false);
    }//GEN-LAST:event_catfMouseClicked

    private void catfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catfActionPerformed
    
    }//GEN-LAST:event_catfActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Botao_Busca;
    private javax.swing.JTextField Campo_Busca;
    private javax.swing.JTable Tabela_Produto;
    private javax.swing.JTextField catf;
    private javax.swing.JLabel data;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marcaf;
    private javax.swing.JTextField nomef;
    // End of variables declaration//GEN-END:variables
 public class horas implements ActionListener{
    @Override
    public void actionPerformed (ActionEvent e){
        Calendar c = Calendar.getInstance();
        hora.setText(String.format("%1$tH:%1$tM:%1$tS", c));
    }
}
}
