/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ValidaDao;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author guigu
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        URL caminhoIcone = getClass().getResource("/img/Logo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senha = new javax.swing.JPasswordField();
        Entrar = new javax.swing.JLabel();
        Botao_2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Tela_Login_01 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);

        senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        senha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        getContentPane().add(senha);
        senha.setBounds(533, 268, 210, 50);

        Entrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Entrar.setText("Entrar");
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                EntrarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarMouseClicked(evt);
            }
        });
        Entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EntrarKeyPressed(evt);
            }
        });
        getContentPane().add(Entrar);
        Entrar.setBounds(551, 380, 80, 30);

        Botao_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Botao_2.setForeground(new java.awt.Color(255, 255, 255));
        Botao_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Botao_2.setText("Limpar");
        Botao_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Botao_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao_2MouseClicked(evt);
            }
        });
        Botao_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Botao_2KeyPressed(evt);
            }
        });
        getContentPane().add(Botao_2);
        Botao_2.setBounds(672, 380, 80, 30);

        usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        getContentPane().add(usuario);
        usuario.setBounds(533, 163, 210, 50);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("x");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 0, 13, 29);

        Tela_Login_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        Tela_Login_01.setPreferredSize(new java.awt.Dimension(807, 509));
        getContentPane().add(Tela_Login_01);
        Tela_Login_01.setBounds(0, 0, 820, 510);

        setSize(new java.awt.Dimension(816, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void EntrarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_EntrarAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_EntrarAncestorAdded

    private void Botao_2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Botao_2KeyPressed

    }//GEN-LAST:event_Botao_2KeyPressed

    private void EntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntrarKeyPressed

    }//GEN-LAST:event_EntrarKeyPressed

    private void EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseClicked
       ValidaDao dao = new ValidaDao();
       
       if(dao.checkLoginFun(usuario.getText(), String.valueOf(senha.getPassword()))){
           new HomeFun().setVisible(true);
           this.dispose();
       }else if(dao.checkLoginCli(usuario.getText(), String.valueOf(senha.getPassword()))){
           new HomeCli().setVisible(true);
           this.dispose();
       }
       else if(dao.checkLoginAdmin(usuario.getText(), String.valueOf(senha.getPassword()))){
           new HomeAdm().setVisible(true);
           this.dispose();
       }
       else if(usuario.getText().trim().isEmpty() || senha.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha todos os campos! ");
       }
       else{
            JOptionPane.showMessageDialog(null, "Login ou Senha incorreta!");
       }

    }   

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
        }
    }//GEN-LAST:event_EntrarMouseClicked

    private void Botao_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao_2MouseClicked
        usuario.setText("");
        senha.setText("");
    }//GEN-LAST:event_Botao_2MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Botao_2;
    private javax.swing.JLabel Entrar;
    private javax.swing.JLabel Tela_Login_01;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
