/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class Produtos extends javax.swing.JFrame {
      /**
     * Creates new form Produtos
     */
    Timer tm;
    int x = 0;
    //Images Path In Array
    String[] list = {
                      "../ProjetoMVC/src/img/Produtos/P23.png",//0
                      "../ProjetoMVC/src/img/Produtos/P16.png",//1
                      "../ProjetoMVC/src/img/Produtos/P22.png",//2
                      "../ProjetoMVC/src/img/Produtos/P21.png",//3
                      "../ProjetoMVC/src/img/Produtos/P27.png",//4
                      "../ProjetoMVC/src/img/Produtos/P20.png",//5
                      "../ProjetoMVC/src/img/Produtos/P25.png"//6
                    };
    public Produtos() {
        initComponents();
            new Thread(){
            public void run(){
            int x = 0;
            int y = texto.getLocation().y;
            
            while(true){
            x++;
            if(x > getWidth()){
            x = 0;
                    }
            texto.setLocation(x,y);
                try {
                    sleep(10);
                } catch (Exception e) {
                }
                }
            }
            }.start();
            
        URL caminhoIcone = getClass().getResource("/img/Logo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        Date da = new Date();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd / MM / YYYY"); 
        data.setText(formato.format(da));
        
        Timer t = new Timer(1000,new view.Produtos.horas());
        t.start();
        

        //Call The Function SetImageSize
        SetImageSize(6);
               //set a timer
        tm = new Timer(1000,new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SetImageSize(x);
                x += 1;
                if(x >= list.length )
                    x = 0; 
            }
        });
        tm.start();

    }
    //create a function to resize the image 
    public void SetImageSize(int i){
        ImageIcon icon = new ImageIcon(list[i]);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(pic.getWidth(), pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImc = new ImageIcon(newImg);
        pic.setIcon(newImc);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        voltar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos");
        setResizable(false);
        getContentPane().setLayout(null);

        data.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(data);
        data.setBounds(650, 20, 110, 30);

        hora.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(hora);
        hora.setBounds(540, 20, 80, 20);

        voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 0, 0));
        voltar.setText("voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(440, 440, 50, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Clique aqui para");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 440, 120, 20);
        getContentPane().add(pic);
        pic.setBounds(320, 170, 230, 160);

        texto.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 51, 51));
        texto.setText("Tudo com 50% de desconto!");
        getContentPane().add(texto);
        texto.setBounds(220, 370, 390, 40);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("x");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 0, 13, 29);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Produtos.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, -10, 810, 520);

        setSize(new java.awt.Dimension(790, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
  
        HomeCli tp = new HomeCli();
        dispose();
        tp.setVisible(true);
    }//GEN-LAST:event_voltarMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel data;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables

 public class horas implements ActionListener{
    @Override
    public void actionPerformed (ActionEvent e){
        Calendar c = Calendar.getInstance();
        hora.setText(String.format("%1$tH:%1$tM:%1$tS", c));
    }
}}
